blueprint:
  name: Mobile app - Request Location Update
  description: >-
    You can force a device to attempt to report its location by sending a special notification. 
    The notification is not visible to the device owner and only works when the app is running or in the background. 
    On success the sensor.last_update_trigger will change to "Push Notification".
  domain: script

  input:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app

mode: restart

sequence:
  - alias: "Send notification"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: "request_location_update"
