blueprint:
  name: Mobile app - ringer mode
  description: >-
    On Android you can control the devices ringer mode 
    by sending message: command_ringer_mode with an appropriate title.
    Certain devices will need to grant a special permission that will appear 
    upon the first command received if the permission was not already granted. 
    This is the same permission as Do Not Disturb up above. 
    If the device has Do Not Disturb enabled then setting to normal or vibrate will turn it off. 
    If the device does not have Do Not Disturb enabled then silent will turn it on.
  domain: script

  input:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app

    ringer_mode:
      name:  Ringer mode
      selector:
        select:
          options:
            - normal
            - silent
            - vibrate

variables:
  title: !input ringer_mode

mode: restart

sequence:
  - alias: "Send notification"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    title: "{{ title }}"
    message: "command_ringer_mode"
